# Netlify configuration for Next.js (App Router)
# Docs: https://docs.netlify.com/integrations/frameworks/next-js/overview/

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Use a modern Node runtime supported by Next 15
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  # Ensure ESM bundling for Next route handlers and faster builds
  node_bundler = "esbuild"
